apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
  labels:
    component : {{ .Values.component }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    component: {{ .Values.component }}
